language: node_js
node_js:
  - 10.15.3
os:
  - osx
notifications:
  email: false
install:
  - yarn install
jobs:
  include:
    - stage: "Lint, Test and Build"
    - script: yarn lint && yarn test && yarn generate
    - stage: "Staging"
    - script: yarn generate:prod
      deploy:
        provider: firebase
        skip_cleanup: true
        token: $FIREBASE_TOKEN
        project: "nwhacks-2019"
        on:
          branch: dev
    - stage: Deploy
      script: yarn generate:prod && echo "2020.nwhacks.io" >> dist/CNAME
      deploy:
        provider: pages
        skip_cleanup: true
        github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
        keep_history: true
        local_dir: dist
        on:
          branch: master
stages:
  - "Lint, Test and Build"
  - name: Staging
    if: branch = dev
  - name: Deploy
    if: branch = master
